save current work on room zero provisioning

diff --git a/ansible/roles/room_zero/tasks/main.yml b/ansible/roles/room_zero/tasks/main.yml
--- a/ansible/roles/room_zero/tasks/main.yml
+++ b/ansible/roles/room_zero/tasks/main.yml
@@ -1,2 +1,543 @@
 ---
 # TODO with ./utils/kind/room-zero/provision.room.zero.sh
+
+##########################################
+##########################################
+##########################################
+### Check role provided params
+
+# should_force_recreate_room_zero
+- name: "Set fact Should force recreate Room Zero?"
+  ansible.builtin.set_fact:
+    should_force_recreate_room_zero: "{{ force_recreate_room_zero  | default('false') }}"
+
+- name: "Print fact Should force recreate Room Zero?"
+  ansible.builtin.debug:
+    var: should_force_recreate_room_zero
+    verbosity: 2
+
+# desired_room_zero_container_name
+- name: "Set fact desired Room Zero Container Name"
+  ansible.builtin.set_fact:
+    desired_room_zero_container_name: "{{ room_zero_container_name | default('room_zero') }}"
+
+- name: "Print fact desired Room Zero Container Name"
+  ansible.builtin.debug:
+    var: desired_room_zero_container_name
+    verbosity: 2
+
+# docker compose file name:
+# 
+- name: "Set fact desired Docker Compose File Name"
+  ansible.builtin.set_fact:
+    desired_docker_compose_file_name: "{{ room_zero_docker_compose_file_name | default('docker-compose.room.zero.yaml') }}"
+
+- name: "Print fact desired Docker Compose File Name"
+  ansible.builtin.debug:
+    var: desired_docker_compose_file_name
+    verbosity: 2
+# desired_room_zero_home
+- name: "Set fact desired Room Zero Home location"
+  ansible.builtin.set_fact:
+    desired_room_zero_home: "{{ room_zero_home }}"
+
+- name: "Print fact desired Room Zero Home location"
+  ansible.builtin.debug:
+    var: desired_room_zero_home
+    verbosity: 2
+
+# desired_room_zero_bind_addr
+- name: "Set fact desired Room Zero Bind Address"
+  ansible.builtin.set_fact:
+    desired_room_zero_bind_addr: "{{ room_zero_bind_addr }}"
+
+- name: "Print fact desired Room Zero Bind Address"
+  ansible.builtin.debug:
+    var: desired_room_zero_bind_addr
+    verbosity: 2
+
+# desired_room_zero_non_routed_ip_addr
+- name: "Set fact desired Room Zero Private IP Address"
+  ansible.builtin.set_fact:
+    desired_room_zero_non_routed_ip_addr: "{{ room_zero_non_routed_ip_addr }}"
+
+- name: "Print fact desired Room Zero Private IP Address"
+  ansible.builtin.debug:
+    var: desired_room_zero_non_routed_ip_addr
+    verbosity: 2
+
+# desired_knd_net_name
+- name: "Set fact desired Kind Network Name"
+  ansible.builtin.set_fact:
+    desired_knd_net_name: "{{ knd_net_name }}"
+
+- name: "Print fact desired Kind Network Name"
+  ansible.builtin.debug:
+    var: desired_knd_net_name
+    verbosity: 2
+
+# desired_openbao_fqdn
+- name: "Set fact desired OpenBAO FQDN"
+  ansible.builtin.set_fact:
+    desired_openbao_fqdn: "{{ pesto_openbao_fqdn  | default('openbao.pesto.io') }}"
+
+- name: "Print fact desired OpenBAO FQDN"
+  ansible.builtin.debug:
+    var: desired_openbao_fqdn
+    verbosity: 2
+
+# desired_openbao_tls_cert_path
+- name: "Set fact desired OpenBAO public Certificate File Path"
+  ansible.builtin.set_fact:
+    desired_openbao_tls_cert_path: "{{ openbao_tls_cert_path }}"
+
+- name: "Print fact desired OpenBAO public Certificate File Path"
+  ansible.builtin.debug:
+    var: desired_openbao_tls_cert_path
+    verbosity: 2
+
+# desired_openbao_tls_cert_key_path
+- name: "Set fact desired OpenBAO Certificate Private Key File Path"
+  ansible.builtin.set_fact:
+    desired_openbao_tls_cert_key_path: "{{ openbao_tls_cert_key_path }}"
+
+- name: "Print fact desired OpenBAO Certificate Private Key File Path"
+  ansible.builtin.debug:
+    var: desired_openbao_tls_cert_key_path
+    verbosity: 2
+
+##########################################
+##########################################
+##########################################
+### Check all params are set
+### 
+- name: "Check all params are set"
+  become: true
+  ansible.builtin.shell: |
+    # should_force_recreate_room_zero
+    export SHOULD_FORCE_RECREATE_ROOM_ZERO='{{ should_force_recreate_room_zero }}'
+    echo " SHOULD_FORCE_RECREATE_ROOM_ZERO = [${SHOULD_FORCE_RECREATE_ROOM_ZERO}] "
+    if [ "x${SHOULD_FORCE_RECREATE_ROOM_ZERO}" == "x" ]; then
+      echo " ERROR - SHOULD_FORCE_RECREATE_ROOM_ZERO is not set"
+      exit 7
+    fi;
+    # desired_room_zero_container_name
+    export DESIRED_ROOM_ZERO_CONTAINER_NAME='{{ desired_room_zero_container_name }}'
+    echo " DESIRED_ROOM_ZERO_CONTAINER_NAME = [${DESIRED_ROOM_ZERO_CONTAINER_NAME}] "
+    if [ "x${DESIRED_ROOM_ZERO_CONTAINER_NAME}" == "x" ]; then
+      echo " ERROR - DESIRED_ROOM_ZERO_CONTAINER_NAME is not set"
+      exit 7
+    fi;
+    # desired_room_zero_home
+    export DESIRED_ROOM_ZERO_HOME='{{ desired_room_zero_home }}'
+    echo " DESIRED_ROOM_ZERO_HOME = [${DESIRED_ROOM_ZERO_HOME}] "
+    if [ "x${DESIRED_ROOM_ZERO_HOME}" == "x" ]; then
+      echo " ERROR - DESIRED_ROOM_ZERO_HOME is not set"
+      exit 7
+    fi;
+    # desired_room_zero_bind_addr
+    export DESIRED_ROOM_ZERO_BIND_ADDR='{{ desired_room_zero_bind_addr }}'
+    echo " DESIRED_ROOM_ZERO_BIND_ADDR = [${DESIRED_ROOM_ZERO_BIND_ADDR}] "
+    if [ "x${DESIRED_ROOM_ZERO_BIND_ADDR}" == "x" ]; then
+      echo " ERROR - DESIRED_ROOM_ZERO_BIND_ADDR is not set"
+      exit 7
+    fi;
+    # desired_room_zero_non_routed_ip_addr
+    export DESIRED_ROOM_ZERO_NON_ROUTED_IP_ADDR='{{ desired_room_zero_non_routed_ip_addr }}'
+    echo " DESIRED_ROOM_ZERO_NON_ROUTED_IP_ADDR = [${DESIRED_ROOM_ZERO_NON_ROUTED_IP_ADDR}] "
+    if [ "x${DESIRED_ROOM_ZERO_NON_ROUTED_IP_ADDR}" == "x" ]; then
+      echo " ERROR - DESIRED_ROOM_ZERO_NON_ROUTED_IP_ADDR is not set"
+      exit 7
+    fi;
+    # desired_knd_net_name
+    export DESIRED_KND_NET_NAME='{{ desired_knd_net_name }}'
+    echo " DESIRED_KND_NET_NAME = [${DESIRED_KND_NET_NAME}] "
+    if [ "x${DESIRED_KND_NET_NAME}" == "x" ]; then
+      echo " ERROR - DESIRED_KND_NET_NAME is not set"
+      exit 7
+    fi;
+    # desired_openbao_fqdn
+    export DESIRED_OPENBAO_FQDN='{{ desired_openbao_fqdn }}'
+    echo " DESIRED_OPENBAO_FQDN = [${DESIRED_OPENBAO_FQDN}] "
+    if [ "x${DESIRED_OPENBAO_FQDN}" == "x" ]; then
+      echo " ERROR - DESIRED_OPENBAO_FQDN is not set"
+      exit 7
+    fi;
+    # desired_openbao_tls_cert_path
+    export DESIRED_OPENBAO_TLS_CERT_PATH='{{ desired_openbao_tls_cert_path }}'
+    echo " DESIRED_OPENBAO_TLS_CERT_PATH = [${DESIRED_OPENBAO_TLS_CERT_PATH}] "
+    if [ "x${DESIRED_OPENBAO_TLS_CERT_PATH}" == "x" ]; then
+      echo " ERROR - DESIRED_OPENBAO_TLS_CERT_PATH is not set"
+      exit 7
+    fi;
+    # desired_openbao_tls_cert_key_path
+    export DESIRED_OPENBAO_TLS_CERT_KEY_PATH='{{ desired_openbao_tls_cert_key_path }}'
+    echo " DESIRED_OPENBAO_TLS_CERT_KEY_PATH = [${DESIRED_OPENBAO_TLS_CERT_KEY_PATH}] "
+    if [ "x${DESIRED_OPENBAO_TLS_CERT_KEY_PATH}" == "x" ]; then
+      echo " ERROR - DESIRED_OPENBAO_TLS_CERT_KEY_PATH is not set"
+      exit 7
+    fi;
+
+    # desired_docker_compose_file_name
+    export DESIRED_DOCKER_COMPOSE_FILE_NAME='{{ desired_docker_compose_file_name }}'
+    echo " DESIRED_DOCKER_COMPOSE_FILE_NAME = [${DESIRED_DOCKER_COMPOSE_FILE_NAME}] "
+    if [ "x${DESIRED_DOCKER_COMPOSE_FILE_NAME}" == "x" ]; then
+      echo " ERROR - DESIRED_DOCKER_COMPOSE_FILE_NAME is not set"
+      exit 7
+    fi;
+  register: check_all_params_output
+- name: "Print stdout of ALl Params Check"
+  ansible.builtin.debug:
+    var: check_all_params_output
+    verbosity: 2
+  when: 
+    - running_os == "debian12"
+##########################################
+##########################################
+##########################################
+### Create Room Zero Home Folder
+### 
+- name: "Create Room Zero Home Folder"
+  become: true
+  ansible.builtin.shell: |
+    export DESIRED_ROOM_ZERO_HOME='{{ desired_room_zero_home }}'
+    echo " DESIRED_ROOM_ZERO_HOME = [${DESIRED_ROOM_ZERO_HOME}] "
+    
+    mkdir -p ${DESIRED_ROOM_ZERO_HOME}
+    chown -R {{ operator_lx_user_name }}:{{ operator_lx_user_name }} ${DESIRED_ROOM_ZERO_HOME}
+    ls -alh ${DESIRED_ROOM_ZERO_HOME}
+  register: create_room_zero_home_folder_output
+  when: 
+    - running_os == "debian12"
+- name: "Print stdout of Room Zero Home Folder Creation"
+  ansible.builtin.debug:
+    var: create_room_zero_home_folder_output
+    verbosity: 2
+  when: 
+    - running_os == "debian12"
+
+##########################################
+##########################################
+##########################################
+### Destroy Room Zero if force recreate
+### 
+- name: "Destroy Room Zero if force recreate"
+  become: true
+  ansible.builtin.shell: |
+    export DESIRED_ROOM_ZERO_HOME='{{ desired_room_zero_home }}'
+    echo " DESIRED_ROOM_ZERO_HOME = [${DESIRED_ROOM_ZERO_HOME}] "
+    export DESIRED_DOCKER_COMPOSE_FILE_NAME='{{ desired_docker_compose_file_name }}'
+    echo " DESIRED_DOCKER_COMPOSE_FILE_NAME = [${DESIRED_DOCKER_COMPOSE_FILE_NAME}] "
+    
+    ls -alh ${DESIRED_ROOM_ZERO_HOME}
+    cd  ${DESIRED_ROOM_ZERO_HOME}
+    ls -alh ${DESIRED_ROOM_ZERO_HOME}/${DESIRED_DOCKER_COMPOSE_FILE_NAME}
+    docker-compose -f ${DESIRED_DOCKER_COMPOSE_FILE_NAME} down || true
+  register: destroy_room_zero_if_force_recreate_output
+  when: 
+    - running_os == "debian12"
+- name: "Print stdout of Destroy Room Zero if force recreate"
+  ansible.builtin.debug:
+    var: destroy_room_zero_if_force_recreate_output
+    verbosity: 2
+  when: 
+    - running_os == "debian12"
+    - should_force_recreate_room_zero
+    # - not not should_force_recreate_room_zero
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+##########################################
+##########################################
+##########################################
+### Provision Room Zero
+### 
+- name: "Provision Room Zero"
+  become: true
+  ansible.builtin.shell: |
+    export DESIRED_ROOM_ZERO_HOME='{{ desired_room_zero_home }}'
+    echo " DESIRED_ROOM_ZERO_HOME = [${DESIRED_ROOM_ZERO_HOME}] "
+    export DESIRED_DOCKER_COMPOSE_FILE_NAME='{{ desired_docker_compose_file_name }}'
+    echo " DESIRED_DOCKER_COMPOSE_FILE_NAME = [${DESIRED_DOCKER_COMPOSE_FILE_NAME}] "
+    
+    ls -alh ${DESIRED_ROOM_ZERO_HOME}
+    cd  ${DESIRED_ROOM_ZERO_HOME}
+    ls -alh ${DESIRED_ROOM_ZERO_HOME}/${DESIRED_DOCKER_COMPOSE_FILE_NAME}
+    # docker-compose -f ${DESIRED_DOCKER_COMPOSE_FILE_NAME} up -d
+
+##################################################
+#### Surgery
+
+
+export OPS_HOME=${HOME}/.room.zero
+
+if [ -d ${OPS_HOME} ]; then
+  cd ${OPS_HOME}
+  docker-compose -f ./docker-compose.room.zero.yaml down || true
+  cd ~
+  rm -fr ${OPS_HOME}
+fi;
+
+mkdir -p ${OPS_HOME}
+
+cd ${OPS_HOME}
+echo "# -------------------- # -------------------- "
+echo "# -------------------- # -------------------- "
+echo "# -------------------- "
+ls -alh ~/.room.zero.env.sh
+echo "# -------------------- "
+echo "# --- content of [~/.room.zero.env.sh]"
+cat -n ~/.room.zero.env.sh
+
+
+chmod +x ~/.room.zero.env.sh
+source ~/.room.zero.env.sh
+
+# export OPENBAO_KND_EXTERNAL_IP=$(cat ~/.room.zero.env.sh | grep 'OPENBAO_KND_EXTERNAL_IP' | awk -F '=' '{ print $NF }')
+# ---
+# The Ip Address of the OpenBAO Service will be the External IP of the Ngonx Ingress Controller 
+export OPENBAO_KND_EXTERNAL_IP=$(kubectl --context kind-openbao-cluster \
+  -n ingress-nginx get services \
+  -l app.kubernetes.io/instance=ingress-nginx \
+  -l app.kubernetes.io/component=controller \
+  --field-selector spec.type=LoadBalancer \
+  -o jsonpath="{.items[0].status.loadBalancer.ingress[0].ip}")
+
+echo "OPENBAO_KND_EXTERNAL_IP=[${OPENBAO_KND_EXTERNAL_IP}]"
+
+
+# ---
+#  
+export KND_NET_NAME=$(cat ~/.room.zero.env.sh | grep 'KND_NET_NAME' | awk -F '=' '{ print $NF }' | sed 's#"##g' | sed "s#'##g")
+
+export ROOM_ZERO_CONTAINER_NAME=${ROOM_ZERO_CONTAINER_NAME:-'room_zero'}
+
+# --- 
+#  ROOM_ZERO_BIND_ADDR: that's the Ip address on which the
+#  internet traffic arrives, basically the same ip address 
+#  than the SSH server binds on. This is exactly either
+#  equals to 0.0.0.0 or, the private Ip Address of the GCP Compute Instance
+# --- 
+export ROOM_ZERO_BIND_ADDR=$(cat ~/.room.zero.env.sh | grep 'ROOM_ZERO_BIND_ADDR' | awk -F '=' '{ print $NF }' | sed 's#"##g' | sed "s#'##g")
+# export ROOM_ZERO_BIND_ADDR='0.0.0.0'
+
+export OPENBAO_FQDN=${OPENBAO_FQDN:-"openbao.pesto.io"}
+echo "# -------------------- "
+echo "# --- After [source ~/.room.zero.env.sh] "
+echo "# --- "
+echo "OPENBAO_KND_EXTERNAL_IP=[$OPENBAO_KND_EXTERNAL_IP]"
+echo "KND_NET_NAME=[${KND_NET_NAME}]"
+echo "ROOM_ZERO_CONTAINER_NAME=[${ROOM_ZERO_CONTAINER_NAME}]"
+echo "# --- "
+echo "# -------------------- "
+echo "# -------------------- # -------------------- "
+echo "# -------------------- # -------------------- "
+
+if [ "x${OPENBAO_KND_EXTERNAL_IP}" == "x" ]; then
+  echo "ERROR!!! The 'OPENBAO_KND_EXTERNAL_IP' env. var. is not set!"
+  exit 7
+fi;
+
+if [ "x${KND_NET_NAME}" == "x" ]; then
+  echo "ERROR!!! The 'KND_NET_NAME' env. var. is not set!"
+  exit 7
+fi;
+
+if [ "x${ROOM_ZERO_CONTAINER_NAME}" == "x" ]; then
+  echo "ERROR!!! The 'ROOM_ZERO_CONTAINER_NAME' env. var. is not set!"
+  exit 7
+fi;
+
+if [ "x${ROOM_ZERO_BIND_ADDR}" == "x" ]; then
+  echo "ERROR!!! The 'ROOM_ZERO_BIND_ADDR' env. var. is not set!"
+  exit 7
+fi;
+
+if [ "x${OPENBAO_FQDN}" == "x" ]; then
+  echo "ERROR!!! The 'OPENBAO_FQDN' env. var. is not set!"
+  exit 7
+fi;
+
+# --- Certificate files
+if [ "x${OPENBAO_TLS_CERT_PATH}" == "x" ]; then
+  echo "ERROR!!! The 'OPENBAO_TLS_CERT_PATH' env. var. is not set!"
+  exit 7
+fi;
+
+if ! [ -f ${OPENBAO_TLS_CERT_PATH} ]; then
+  echo "ERROR - The OPENBAO_TLS_CERT_PATH=[${OPENBAO_TLS_CERT_PATH}] file does not exist, itmust exist"
+  exit 23
+fi;
+
+if [ "x${OPENBAO_TLS_CERT_KEY_PATH}" == "x" ]; then
+  echo "ERROR!!! The 'OPENBAO_TLS_CERT_KEY_PATH' env. var. is not set!"
+  exit 7
+fi;
+
+if ! [ -f ${OPENBAO_TLS_CERT_KEY_PATH} ]; then
+  echo "ERROR - The OPENBAO_TLS_CERT_KEY_PATH=[${OPENBAO_TLS_CERT_KEY_PATH}] file does not exist, itmust exist"
+  exit 23
+fi;
+
+
+
+
+# figlet 'Room Zero'
+
+# the docker-compose of the nginx service we will spin up
+docker-compose -f ./docker-compose.room.zero.yaml down || true
+cat <<EOF >./docker-compose.room.zero.yaml
+version: '3.7'
+
+services:
+  room-zero:
+    image: nginx:1.19.2-alpine
+    hostname: room-zero
+    container_name: ${ROOM_ZERO_CONTAINER_NAME}
+    volumes:
+      - ./nginx.conf:/etc/nginx/nginx.conf:ro
+      - ${OPENBAO_TLS_CERT_PATH}:/etc/nginx/certs/${OPENBAO_FQDN}.cert:ro
+      - ${OPENBAO_TLS_CERT_KEY_PATH}:/etc/nginx/certs/${OPENBAO_FQDN}.key:ro
+    ports:
+      - "${ROOM_ZERO_BIND_ADDR}:80:80"
+      # - "${ROOM_ZERO_BIND_ADDR}:8081:80"
+    networks:
+      room_zero_net:
+        aliases:
+          - room-zero.pesto.io
+
+networks:
+  room_zero_net:
+    driver: bridge
+EOF
+
+#################
+##### OKAY I WILL TRY THAT FIRST VERSION:
+# I still need to geenerate the certs, and do all needed to 
+# place them in container image by docker volumes...
+cat <<EOF >./nginx.conf
+user  nginx;
+worker_processes  auto;
+
+error_log  /var/log/nginx/error.log warn;
+pid        /var/run/nginx.pid;
+
+events {
+    worker_connections  4096;
+}
+
+http {
+    include       /etc/nginx/mime.types;
+    default_type  application/octet-stream; 
+
+    log_format  main  'room-zero-pesto - \$remote_addr - \$remote_user [\$time_local] "\$request" '
+                      '\$status \$body_bytes_sent "\$http_referer" '
+                      '"\$http_user_agent" "\$http_x_forwarded_for"';
+
+    access_log  /var/log/nginx/access.log  main;
+    sendfile        on;
+    keepalive_timeout  65;
+
+    # include /etc/nginx/conf.d/*.conf;
+    
+    upstream openbao {
+        ip_hash;
+        server $OPENBAO_KND_EXTERNAL_IP:443;
+    }
+
+    server {
+        # listen       80;
+        # listen  [::]:80;
+        listen       443 ssl;
+        listen  [::]:443 ssl;
+        # server_name  localhost;
+        # --- 
+        # ${OPENBAO_FQDN}: i would then add in my [/etc/hosts] an entry to map it to the public IP of my VM
+        server_name ${OPENBAO_FQDN};
+        ssl_certificate /etc/nginx/certs/${OPENBAO_FQDN}.cert;
+        ssl_certificate_key /etc/nginx/certs/${OPENBAO_FQDN}.key;
+        # ---
+        # Stronger than the default [ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;] see https://docs.nginx.com/nginx/admin-guide/security-controls/terminating-ssl-http/
+        ssl_protocols TLSv1.2 TLSv1.3;
+        ssl_ciphers "HIGH:!aNULL:!MD5:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256";
+        ssl_prefer_server_ciphers on;
+
+        # To allow special characters in headers
+        ignore_invalid_headers off;
+        # Allow any size file to be uploaded.
+        # Set to a value such as 1000m; to restrict file size to a specific value
+        client_max_body_size 0;
+        # To disable buffering
+        proxy_buffering off;
+        proxy_request_buffering off;
+
+        location / {
+            proxy_set_header Host \$http_host;
+            proxy_set_header X-Real-IP \$remote_addr;
+            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
+            proxy_set_header X-Forwarded-Proto \$scheme;
+            proxy_set_header X-NginX-Proxy true;
+
+            # This is necessary to pass the correct IP to be hashed
+            real_ip_header X-Real-IP;
+
+            proxy_connect_timeout 300;
+            
+            # To support websocket
+            proxy_http_version 1.1;
+            proxy_set_header Upgrade \$http_upgrade;
+            proxy_set_header Connection "upgrade";
+            
+            chunked_transfer_encoding off;
+            
+            # ---
+            #  I will for now assume that 
+            #  the connection between nginx 
+            #  and the reverse-proxied openbao service 
+            #  is NOT secured, and when I want to secure with https encryption that part too, I will use:
+            #  > This for MTLS (client TLS cert authentication, nginx authenticate to the reverse proxied server using a client cert) https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/
+            #  > Or something lighter: NGINX will just need to trust the TLS cert broadcasted by the reverse-proxied openbao 
+            # proxy_pass https://openbao;
+            proxy_pass http://openbao;
+        }
+    }
+}
+EOF
+
+
+docker-compose -f ./docker-compose.room.zero.yaml up -d
+
+
+sleep 3s
+
+figlet 'Connect Room Zero'
+
+docker network connect "${KND_NET_NAME}" "${ROOM_ZERO_CONTAINER_NAME}"
+
+#################################################
+  register: provision_room_zero_output
+  when: 
+    - running_os == "debian12"
+- name: "Print stdout of Provision Room Zero"
+  ansible.builtin.debug:
+    var: provision_room_zero_output
+    verbosity: 2
+  when: 
+    - running_os == "debian12"
+
